/*
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.validation

import org.eclipse.xtext.validation.Check
import net.adempiere.dsl.properties.propMod.Metadata
import net.adempiere.dsl.properties.propMod.PropModPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class PropModValidator extends AbstractPropModValidator {

	public static val INVALID_PACKAGE_NAME = 'invalidName'

	@Check
	def checkPackageName(Metadata propsMetadata) {
		//@Trifon
		if (propsMetadata.packageName !== null && propsMetadata.packageName.length > 0) {
			// Check that package name start with lower case letter
			if (Character.isUpperCase(propsMetadata.packageName.charAt(0))) {
				warning('Package Name should start with a lower letter', 
						PropModPackage.Literals.METADATA__PACKAGE_NAME,
						INVALID_PACKAGE_NAME)
			}
	
			// Check that package name do not contain "-"(minus)
			if (propsMetadata.packageName.contains('-')) {
				error('Package Name MUST not contain "-"', 
						PropModPackage.Literals.METADATA__PACKAGE_NAME,
						INVALID_PACKAGE_NAME)
			}
		}
	}
	
}
