/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.scoping;

import net.adempiere.dsl.properties.scoping.AbstractPropModScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PropModScopeProvider extends AbstractPropModScopeProvider {
}
