/*
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PropModAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("net/adempiere/dsl/properties/parser/antlr/internal/InternalPropMod.tokens");
	}
}
