/*
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.parser.antlr;

import com.google.inject.Inject;
import net.adempiere.dsl.properties.parser.antlr.internal.InternalPropModParser;
import net.adempiere.dsl.properties.services.PropModGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PropModParser extends AbstractAntlrParser {

	@Inject
	private PropModGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPropModParser createParser(XtextTokenStream stream) {
		return new InternalPropModParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PropModel";
	}

	public PropModGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PropModGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
