/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.propMod;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see net.adempiere.dsl.properties.propMod.PropModFactory
 * @model kind="package"
 * @generated
 */
public interface PropModPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "propMod";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.adempiere.net/dsl/properties/PropMod";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "propMod";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PropModPackage eINSTANCE = net.adempiere.dsl.properties.propMod.impl.PropModPackageImpl.init();

  /**
   * The meta object id for the '{@link net.adempiere.dsl.properties.propMod.impl.PropModelImpl <em>Prop Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.adempiere.dsl.properties.propMod.impl.PropModelImpl
   * @see net.adempiere.dsl.properties.propMod.impl.PropModPackageImpl#getPropModel()
   * @generated
   */
  int PROP_MODEL = 0;

  /**
   * The feature id for the '<em><b>Meta Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROP_MODEL__META_DATA = 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROP_MODEL__PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>Prop Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROP_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link net.adempiere.dsl.properties.propMod.impl.MetadataImpl <em>Metadata</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.adempiere.dsl.properties.propMod.impl.MetadataImpl
   * @see net.adempiere.dsl.properties.propMod.impl.PropModPackageImpl#getMetadata()
   * @generated
   */
  int METADATA = 1;

  /**
   * The feature id for the '<em><b>Package Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA__PACKAGE_NAME = 0;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA__PREFIX = 1;

  /**
   * The feature id for the '<em><b>Java Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA__JAVA_CLASS_NAME = 2;

  /**
   * The number of structural features of the '<em>Metadata</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METADATA_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link net.adempiere.dsl.properties.propMod.impl.PropertyDefinitionImpl <em>Property Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.adempiere.dsl.properties.propMod.impl.PropertyDefinitionImpl
   * @see net.adempiere.dsl.properties.propMod.impl.PropModPackageImpl#getPropertyDefinition()
   * @generated
   */
  int PROPERTY_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_DEFINITION__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_DEFINITION__NAME = 1;

  /**
   * The feature id for the '<em><b>Not Null</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_DEFINITION__NOT_NULL = 2;

  /**
   * The number of structural features of the '<em>Property Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link net.adempiere.dsl.properties.propMod.PropertyType <em>Property Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see net.adempiere.dsl.properties.propMod.PropertyType
   * @see net.adempiere.dsl.properties.propMod.impl.PropModPackageImpl#getPropertyType()
   * @generated
   */
  int PROPERTY_TYPE = 3;


  /**
   * Returns the meta object for class '{@link net.adempiere.dsl.properties.propMod.PropModel <em>Prop Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prop Model</em>'.
   * @see net.adempiere.dsl.properties.propMod.PropModel
   * @generated
   */
  EClass getPropModel();

  /**
   * Returns the meta object for the containment reference '{@link net.adempiere.dsl.properties.propMod.PropModel#getMetaData <em>Meta Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Meta Data</em>'.
   * @see net.adempiere.dsl.properties.propMod.PropModel#getMetaData()
   * @see #getPropModel()
   * @generated
   */
  EReference getPropModel_MetaData();

  /**
   * Returns the meta object for the containment reference list '{@link net.adempiere.dsl.properties.propMod.PropModel#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see net.adempiere.dsl.properties.propMod.PropModel#getProperties()
   * @see #getPropModel()
   * @generated
   */
  EReference getPropModel_Properties();

  /**
   * Returns the meta object for class '{@link net.adempiere.dsl.properties.propMod.Metadata <em>Metadata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metadata</em>'.
   * @see net.adempiere.dsl.properties.propMod.Metadata
   * @generated
   */
  EClass getMetadata();

  /**
   * Returns the meta object for the attribute '{@link net.adempiere.dsl.properties.propMod.Metadata#getPackageName <em>Package Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Package Name</em>'.
   * @see net.adempiere.dsl.properties.propMod.Metadata#getPackageName()
   * @see #getMetadata()
   * @generated
   */
  EAttribute getMetadata_PackageName();

  /**
   * Returns the meta object for the attribute '{@link net.adempiere.dsl.properties.propMod.Metadata#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prefix</em>'.
   * @see net.adempiere.dsl.properties.propMod.Metadata#getPrefix()
   * @see #getMetadata()
   * @generated
   */
  EAttribute getMetadata_Prefix();

  /**
   * Returns the meta object for the attribute '{@link net.adempiere.dsl.properties.propMod.Metadata#getJavaClassName <em>Java Class Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Java Class Name</em>'.
   * @see net.adempiere.dsl.properties.propMod.Metadata#getJavaClassName()
   * @see #getMetadata()
   * @generated
   */
  EAttribute getMetadata_JavaClassName();

  /**
   * Returns the meta object for class '{@link net.adempiere.dsl.properties.propMod.PropertyDefinition <em>Property Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Definition</em>'.
   * @see net.adempiere.dsl.properties.propMod.PropertyDefinition
   * @generated
   */
  EClass getPropertyDefinition();

  /**
   * Returns the meta object for the attribute '{@link net.adempiere.dsl.properties.propMod.PropertyDefinition#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see net.adempiere.dsl.properties.propMod.PropertyDefinition#getType()
   * @see #getPropertyDefinition()
   * @generated
   */
  EAttribute getPropertyDefinition_Type();

  /**
   * Returns the meta object for the attribute '{@link net.adempiere.dsl.properties.propMod.PropertyDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see net.adempiere.dsl.properties.propMod.PropertyDefinition#getName()
   * @see #getPropertyDefinition()
   * @generated
   */
  EAttribute getPropertyDefinition_Name();

  /**
   * Returns the meta object for the attribute '{@link net.adempiere.dsl.properties.propMod.PropertyDefinition#isNotNull <em>Not Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Not Null</em>'.
   * @see net.adempiere.dsl.properties.propMod.PropertyDefinition#isNotNull()
   * @see #getPropertyDefinition()
   * @generated
   */
  EAttribute getPropertyDefinition_NotNull();

  /**
   * Returns the meta object for enum '{@link net.adempiere.dsl.properties.propMod.PropertyType <em>Property Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Property Type</em>'.
   * @see net.adempiere.dsl.properties.propMod.PropertyType
   * @generated
   */
  EEnum getPropertyType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PropModFactory getPropModFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link net.adempiere.dsl.properties.propMod.impl.PropModelImpl <em>Prop Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.adempiere.dsl.properties.propMod.impl.PropModelImpl
     * @see net.adempiere.dsl.properties.propMod.impl.PropModPackageImpl#getPropModel()
     * @generated
     */
    EClass PROP_MODEL = eINSTANCE.getPropModel();

    /**
     * The meta object literal for the '<em><b>Meta Data</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROP_MODEL__META_DATA = eINSTANCE.getPropModel_MetaData();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROP_MODEL__PROPERTIES = eINSTANCE.getPropModel_Properties();

    /**
     * The meta object literal for the '{@link net.adempiere.dsl.properties.propMod.impl.MetadataImpl <em>Metadata</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.adempiere.dsl.properties.propMod.impl.MetadataImpl
     * @see net.adempiere.dsl.properties.propMod.impl.PropModPackageImpl#getMetadata()
     * @generated
     */
    EClass METADATA = eINSTANCE.getMetadata();

    /**
     * The meta object literal for the '<em><b>Package Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METADATA__PACKAGE_NAME = eINSTANCE.getMetadata_PackageName();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METADATA__PREFIX = eINSTANCE.getMetadata_Prefix();

    /**
     * The meta object literal for the '<em><b>Java Class Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METADATA__JAVA_CLASS_NAME = eINSTANCE.getMetadata_JavaClassName();

    /**
     * The meta object literal for the '{@link net.adempiere.dsl.properties.propMod.impl.PropertyDefinitionImpl <em>Property Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.adempiere.dsl.properties.propMod.impl.PropertyDefinitionImpl
     * @see net.adempiere.dsl.properties.propMod.impl.PropModPackageImpl#getPropertyDefinition()
     * @generated
     */
    EClass PROPERTY_DEFINITION = eINSTANCE.getPropertyDefinition();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_DEFINITION__TYPE = eINSTANCE.getPropertyDefinition_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_DEFINITION__NAME = eINSTANCE.getPropertyDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Not Null</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_DEFINITION__NOT_NULL = eINSTANCE.getPropertyDefinition_NotNull();

    /**
     * The meta object literal for the '{@link net.adempiere.dsl.properties.propMod.PropertyType <em>Property Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see net.adempiere.dsl.properties.propMod.PropertyType
     * @see net.adempiere.dsl.properties.propMod.impl.PropModPackageImpl#getPropertyType()
     * @generated
     */
    EEnum PROPERTY_TYPE = eINSTANCE.getPropertyType();

  }

} //PropModPackage
