/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.propMod;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prop Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link net.adempiere.dsl.properties.propMod.PropModel#getMetaData <em>Meta Data</em>}</li>
 *   <li>{@link net.adempiere.dsl.properties.propMod.PropModel#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see net.adempiere.dsl.properties.propMod.PropModPackage#getPropModel()
 * @model
 * @generated
 */
public interface PropModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Meta Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Meta Data</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Meta Data</em>' containment reference.
   * @see #setMetaData(Metadata)
   * @see net.adempiere.dsl.properties.propMod.PropModPackage#getPropModel_MetaData()
   * @model containment="true"
   * @generated
   */
  Metadata getMetaData();

  /**
   * Sets the value of the '{@link net.adempiere.dsl.properties.propMod.PropModel#getMetaData <em>Meta Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Meta Data</em>' containment reference.
   * @see #getMetaData()
   * @generated
   */
  void setMetaData(Metadata value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link net.adempiere.dsl.properties.propMod.PropertyDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Properties</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see net.adempiere.dsl.properties.propMod.PropModPackage#getPropModel_Properties()
   * @model containment="true"
   * @generated
   */
  EList<PropertyDefinition> getProperties();

} // PropModel
