/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.validation;

import net.adempiere.dsl.properties.propMod.Metadata;
import net.adempiere.dsl.properties.propMod.PropModPackage;
import net.adempiere.dsl.properties.validation.AbstractPropModValidator;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PropModValidator extends AbstractPropModValidator {
  public final static String INVALID_PACKAGE_NAME = "invalidName";
  
  @Check
  public void checkPackageName(final Metadata propsMetadata) {
    if (((propsMetadata.getPackageName() != null) && (propsMetadata.getPackageName().length() > 0))) {
      boolean _isUpperCase = Character.isUpperCase(propsMetadata.getPackageName().charAt(0));
      if (_isUpperCase) {
        this.warning("Package Name should start with a lower letter", 
          PropModPackage.Literals.METADATA__PACKAGE_NAME, 
          PropModValidator.INVALID_PACKAGE_NAME);
      }
      boolean _contains = propsMetadata.getPackageName().contains("-");
      if (_contains) {
        this.error("Package Name MUST not contain \"-\"", 
          PropModPackage.Literals.METADATA__PACKAGE_NAME, 
          PropModValidator.INVALID_PACKAGE_NAME);
      }
    }
  }
}
