/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.ide;

import net.adempiere.dsl.properties.ide.AbstractPropModIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PropModIdeModule extends AbstractPropModIdeModule {
}
