/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import net.adempiere.dsl.properties.PropModRuntimeModule;
import net.adempiere.dsl.properties.PropModStandaloneSetup;
import net.adempiere.dsl.properties.ide.PropModIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PropModIdeSetup extends PropModStandaloneSetup {
  @Override
  public Injector createInjector() {
    PropModRuntimeModule _propModRuntimeModule = new PropModRuntimeModule();
    PropModIdeModule _propModIdeModule = new PropModIdeModule();
    return Guice.createInjector(Modules2.mixin(_propModRuntimeModule, _propModIdeModule));
  }
}
