/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.ui;

import net.adempiere.dsl.properties.ui.AbstractPropModUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PropModUiModule extends AbstractPropModUiModule {
  public PropModUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
