/*
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link PropModWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractPropModWebModule extends DefaultWebModule {

}
