/*
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.ui;

import com.google.inject.Injector;
import net.adempiere.dsl.properties.spring.ui.internal.SpringActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PropModExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SpringActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SpringActivator activator = SpringActivator.getInstance();
		return activator != null ? activator.getInjector(SpringActivator.NET_ADEMPIERE_DSL_PROPERTIES_PROPMOD) : null;
	}

}
