/*
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.ui.tests;

import com.google.inject.Injector;
import net.adempiere.dsl.properties.spring.ui.internal.SpringActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PropModUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpringActivator.getInstance().getInjector("net.adempiere.dsl.properties.PropMod");
	}

}
