/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties;

import net.adempiere.dsl.properties.PropModStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PropModStandaloneSetup extends PropModStandaloneSetupGenerated {
  public static void doSetup() {
    new PropModStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
