/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties;

import net.adempiere.dsl.properties.AbstractPropModRuntimeModule;
import net.adempiere.dsl.properties.generator.PropModOutputConfigurationProvider;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PropModRuntimeModule extends AbstractPropModRuntimeModule {
  public Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider() {
    return PropModOutputConfigurationProvider.class;
  }
}
