/*
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPropModScopeProvider extends DelegatingScopeProvider {
}
