/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.serializer;

import net.adempiere.dsl.properties.serializer.AbstractPropModSemanticSequencer;

@SuppressWarnings("all")
public class PropModSemanticSequencer extends AbstractPropModSemanticSequencer {
}
