/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.serializer;

import net.adempiere.dsl.properties.serializer.AbstractPropModSyntacticSequencer;

@SuppressWarnings("all")
public class PropModSyntacticSequencer extends AbstractPropModSyntacticSequencer {
}
