/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.ui.wizard;

import net.adempiere.dsl.properties.ui.wizard.PropModelMavenBuildProject;
import org.eclipse.xtext.ui.wizard.template.AbstractProjectTemplate;
import org.eclipse.xtext.ui.wizard.template.IProjectTemplateProvider;

/**
 * Create a list with all project templates to be shown in the template new project wizard.
 * 
 * Each template is able to generate one or more projects. Each project can be configured such that any number of files are included.
 */
@SuppressWarnings("all")
public class PropModProjectTemplateProvider implements IProjectTemplateProvider {
  @Override
  public AbstractProjectTemplate[] getProjectTemplates() {
    PropModelMavenBuildProject _propModelMavenBuildProject = new PropModelMavenBuildProject();
    return new AbstractProjectTemplate[] { _propModelMavenBuildProject };
  }
}
