/*
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PropModStandaloneSetup extends PropModStandaloneSetupGenerated {

	def static void doSetup() {
		new PropModStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
