/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class PropModDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
