/*
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class PropModWebModule extends AbstractPropModWebModule {
}
