/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.web;

import net.adempiere.dsl.properties.web.AbstractPropModWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class PropModWebModule extends AbstractPropModWebModule {
}
