/**
 * generated by Xtext 2.14.0
 */
package net.adempiere.dsl.properties.ui.contentassist;

import net.adempiere.dsl.properties.ui.contentassist.AbstractPropModProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PropModProposalProvider extends AbstractPropModProposalProvider {
}
